http_port 80

https_port 443 intercept ssl-bump \
    cert=/etc/squid/root_mitm_headroom.pem \
    generate-host-certificates=on \
    dynamic_cert_mem_cache_size=4MB

sslcrtd_program /usr/lib/squid/security_file_certgen -s /var/spool/squid/ssldb -M 4MB

ssl_bump bump all

acl localnet src 10.0.0.0/8
http_access allow localnet
http_access deny all

cache_peer 127.0.0.1 parent 9000 0 no-query originserver tls tlsflags=DONT_VERIFY_PEER,DONT_VERIFY_DOMAIN name=backend_nginx
cache_peer_access backend_nginx allow all
never_direct allow all
